### ISSUE TITLE
两个固件之间的区别

### ISSUE THREAD

**Issue by LincoZ** [AngelaCooljx/Actions-rax3000m-emmc#11]
第一次接触rx3000m刷openwrt
不知道release里面两个固件之间的一个区别
![微信图片_20240820163247](https://github.com/user-attachments/assets/86fe0002-ec2d-42d5-9aa3-f8770ec2a71f)

**Comment by KawaiiHachimi** [comment]
kernel.bin不挂载overlay重启不保留配置，一般没必要使用，sysupgrade.bin可以OpenWrt直接更新或者uboot刷写，用这个就好
