### ISSUE TITLE
OPK安装软件很慢，很多软件安装不成功。

### ISSUE THREAD

**Issue by SIX6789** [AngelaCooljx/Actions-rax3000m-emmc#4]
23.05.0-rc4版本的安装软件很快，但这个snapshots版本安装软件很慢，还有很多软件安装不上或提示kernel_5.15和软件要求的版本不一至如DOCKER。
就算是如提示安装好"kernel_5.15.*_aarch64_cortex-a53.ipk" 后DOCKER也安装不上。

**Comment by KawaiiHachimi** [comment]
要 docker 在 config 自行添加相关 CONFIG 选项集成相关软件包或内核模块，要切换 v23.05.0-rc4 版本在 action 工作流配置文件 git clone xxx 下面添加 `git checkout v23.05.0-rc4`， 至于安装好 "kernel_5.15.*_aarch64_cortex-a53.ipk" 后还是装不上 docker 自行排查当前内核版本号是否匹配，截至目前为 5.15.137 ，"kernel_5.15.*_aarch64_cortex-a53.ipk"的作用就是让同版本号内核后面的 hash 值与软件源的匹配以能够正常安装 kmod 类型 ipk
