### ISSUE TITLE
关于rax3000m NAND版的替换eeprom的问题

### ISSUE THREAD

**Issue by GD-Slime** [AngelaCooljx/Actions-rax3000m-emmc#7]
我目前在使用nand版本(128M闪存)的rax3000m。
在已经在fork中正常编译出无线正常的nand版本的固件后，我发现无线功率没有提高。
我查看了工作流的文件，并在替换eeprom的步骤里添加了这样一行： 
`sed -i 's/rax3000m-emmc/rax3000m-nand/' openwrt/target/linux/mediatek/mt7981/base-files/lib/preinit/90_extract_caldata` 
试图把型号修改为nand版本。 但是失败了，没有变化。
全网好像没有这方面的资料，237大佬也是直接放出固件。

如果您有时间的话希望能点拨一下，或者介绍一下这个替换eeprom的原理和步骤，感激不尽！

**Comment by KawaiiHachimi** [comment]
emmc版本读eeprom是先导出分区到/lib/firmware再读文件，nand版本直接读的分区，要改直接改成读firmware同时保留原mac地址参考这条提交修改，https://github.com/padavanonly/immortalwrt-mt798x/commit/32ccfa4af7cd8eb6193c0394a06f5d32ac49c1f7

**Comment by GD-Slime** [comment]
感谢回复！
